export const IMAGES = {
  LOGO: "/images/logo.png",
  SLIDE1: "/images/slide1.jpg",
  SLIDE2: "/images/slide2.jpg",
  SLIDE3: "/images/slide3.jpg",
  SLIDE4: "/images/slide4.jpg",
  SLIDE5: "/images/slide5.jpg",
  SLIDE6: "/images/slide6.jpg",
  SLIDE7: "/images/slide7.jpg",
  SLIDE8: "/images/slide8.jpg",
  AVATER_1: "/images/avatar1.png",
  AVATER_2: "/images/favicon.png",
  CONTACT_US: "/images/contact.png",
  ASSOCIATE: "/images/ass.jpg",
  NOTFOUND: "/images/404.png",
  ROBOT: "/images/robot.png",

  // images for student
  IMG0: "/images/img0.jpg",
  IMG1: "/images/img1.jpg",
  IMG2: "/images/img2.jpg",
  IMG3: "/images/img3.jpg",
  IMG4: "/images/img4.jpg",
  IMG5: "/images/img5.jpg",
  IMG6: "/images/img6.jpg",
  IMG7: "/images/img7.jpg",
  IMG8: "/images/img8.jpg",
  IMG9: "/images/img9.jpg",
  IMG10: "/images/img10.jpg",
  IMG11: "/images/img11.jpg",
  IMG12: "/images/img12.jpg",
  IMG13: "/images/img13.jpg",
  IMG14: "/images/img14.jpg",

  // associate pictures
  ASS1: "/images/ass1.jpg",
  ASS2: "/images/ass2.jpg",
  ASS3: "/images/ass3.jpg",
  ASS4: "/images/ass4.jpg",
  ASS5: "/images/ass5.jpg",
  ASS6: "/images/ass6.jpg",
  ASS7: "/images/ass7.jpg",
  ASS8: "/images/ass8.jpg",
  ASS9: "/images/ass9.jpg",
  ASS10: "/images/ass10.jpg",
};
